### ISSUE TITLE
Training params?

### ISSUE THREAD

**Issue by aaronrmm** [dredwardhyde/gpt-neo-fine-tuning-example#1]
This is awesome! Thank you for showing the VRAM to show training requirements and speed. Only one thing I didn't find:
Do you remember the max_length of the tokenized Netflix titles?

[max_length = max([len(tokenizer.encode(description)) for description in descriptions])](https://github.com/dredwardhyde/gpt-neo-fine-tuning-example/blob/8e59dcbdc9c796ddb50b9e98c3f221a9401a65a4/gpt_neo_xl_deepspeed.py#L18)

**Comment by dredwardhyde** [comment]
Of course, **max_length** was **62**: 

![Screenshot from 2021-04-09 08-18-21](https://user-images.githubusercontent.com/8986329/114132049-50d92f00-990c-11eb-9cb4-fce05023dfc9.png)
