### ISSUE TITLE
2.7B model hardware requirements

### ISSUE THREAD

**Issue by mallorbc** [dredwardhyde/gpt-neo-fine-tuning-example#5]
I have tried fine tunning this 2.7B parameter model with my RTX 3090 and with 64 GB of RAM.  Looking at system resources, I am exhausting all of my RAM before the program is killed.  My question is what hardware was used in this repo?  Specifically, how much RAM is required to train the 2.7B model?

**Comment by dredwardhyde** [comment]
Hi, training required 70-75GB of RAM (I have 128)

**Comment by mallorbc** [comment]
Thanks

**Comment by dredwardhyde** [comment]
Nope, I have 5950x

**Comment by g-simmons** [comment]
@mallorbc @dredwardhyde Would either of you happen to have estimates on training time on a single 3090, or 2x 3090? I am looking to finetune a 2.7B model and wondering how long I can expect training to take, in terms of hours per billion tokens, for example. Thanks!

**Comment by g-simmons** [comment]
Would I be correct to upper-bound the netflix dataset size as 62*7008 = 435k tokens? Over 5 epochs the model would see 2.1m tokens, and the training log looks like it took about 2hours 15 minutes... so maybe 1m tokens per hour is reasonable as a rough estimate?

**Comment by dredwardhyde** [comment]
Hi, yep, I guess you are right

**Comment by g-simmons** [comment]
@dredwardhyde thanks!
