### ISSUE TITLE
GPU Memory Requirements

### ISSUE THREAD

**Issue by AaronWatson2975** [dredwardhyde/gpt-neo-fine-tuning-example#8]
## Question
Just a quick question, is anyone aware of how much GPU memory is required to train these models?  I'm on Kaggle with a P100(16GB) and I can't see to to call `.train()` without running out memory on any of the 3 models available.

I've tried with the 2.7B, 1.3B and 125M param models and I get the same result with all 3, surely a P100 can handle the 125M model.  🤔 

I might order some more RAM for my home server and try this again on a CPU, I saw from the other post here it looks like I'll need at least 75GB which isn't bad at all, plus it gives me an excuse to upgrade it haha.

```
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 15.90 GiB total capacity; 14.71 GiB already allocated; 77.75 MiB free; 14.95 GiB reserved in total by PyTorch)
```

**Comment by theainerd** [comment]
Hello @AaronWatson2975,  were you able to train it on a 75GB RAM machine. ??

**Comment by AaronWatson2975** [comment]
Hey, thanks for reaching out!  I did not end up getting a chance to test it after, as such I'll be closing the issue.
